### ISSUE TITLE
Update Minio Template

### ISSUE THREAD

**Issue by chi110r** [cheesemarathon/docker-templates#3]
The Minio Template needs an Update

The Environment variables are deprecated and there is an new Consol (web UI) port which can be specified in de Post Argument `server /data --console-address ":9001"`

`WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated. Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
API: http://172.17.0.11:9000 http://127.0.0.1:9000
Console: http://172.17.0.11:9001 http://127.0.0.1:9001
Documentation: https://docs.min.io`

**Comment by ghost** [comment]
Done 69df469
